### ISSUE TITLE
Fix hours check in `is_args_valid`

### ISSUE THREAD

**Issue by Gguigre** [SegFault42/Tgv_Max_Alert#2]
Hello @SegFault42 

In the `is_args_valid` check, 
the `hours` check is `(int(hour[0]) > 0 and int(hour[0]) < 24 and int(hour[1]) > 0 and int(hour[1]) < 24)`

it should be
`(int(hour[0]) > 0 and int(hour[0]) < 24 and int(hour[1]) > 0 and int(hour[1]) < 60)`

since the minutes var (`hour[1]`) can be more than 24

**Comment by SegFault42** [comment]
Merged :D, thank you
